### ISSUE TITLE
Please add the college information.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/iiit-b-gfg-webinar#1]
The college information is missing in this repository.

Someone please add it.

**Comment by ghost** [comment]
IIIT BHUBANEAWAR

**Comment by PrinceX04** [comment]
i want to do it

**Comment by praveenscience** [comment]
Okay @PrinceX04 I'll assign it to you.

**Comment by RudrakshGupta23** [comment]
Thank for this sir

**Comment by haresh9001** [comment]
IIIT- bh
